# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZmZmZjFhZTdkZmMzOGRiNzM2MzExYWRlYTdmZTYxZDJkMDdmNGI4MDQwMzllMGQ3ZWQ2ZjBiMThkZmY1MWI1MjRiOTY0NmJiYjU2NzQ5OTNmZWFhYWM3YmYxM2Q4MGE5MjMwYTBkMGRjODFhNzYyYWUyZmM0N2I1YzJkY2M2MmQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
